<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **Aula 01 - Criando Objetos com Pandas (DataFrame e Series)**

<br>
<br>

___

**Importação da Biblioteca**

In [1]:
import pandas as pd

**Series** é um array rotulado unidimensional capaz de conter qualquer tipo de dados (inteiros, strings, números de ponto flutuante, objetos Python, etc.). Os rótulos dos eixos são chamados coletivamente de índice.



```
pandas.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)
```

In [8]:
series = pd.Series([1,2,3,4,5,6,7,8,9])

In [9]:
series

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [10]:
series = pd.Series([1, 'Daniela', 1.78])

In [11]:
series

0          1
1    Daniela
2       1.78
dtype: object

In [12]:
series_2 = pd.Series({'a': 1, 'b': 2, 'c': 3})

In [13]:
series_2

a    1
b    2
c    3
dtype: int64

**DataFrame** é uma estrutura de dados tabulares bidimensionais, mutáveis ​​em tamanho e potencialmente heterogêneos.

A estrutura de dados também contém eixos rotulados (linhas e colunas).

```
pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)
```

In [14]:
dicionario_um = {'Nome': ['Pedro', 'Ana', 'Karina', 'Patricia', 'Carlos', 'Felipe', 'José', 'Gustavo', 'Fernando'],
                 'Idade': [20, 21, 19, 18, 23, 21, 27, 30, 22]
                 }

In [15]:
dataframe = pd.DataFrame(dicionario_um)

In [19]:
dataframe.head()

       Nome  Idade
0     Pedro     20
1       Ana     21
2    Karina     19
3  Patricia     18
4    Carlos     23

In [21]:
dataframe.tail(3)

       Nome  Idade
6      José     27
7   Gustavo     30
8  Fernando     22

In [22]:
lista = [['Pedro', 20], 
         ['Ana', 21],
         ['Karina', 19],
         ['Patricia', 18],
         ['Carlos', 23],
         ['Felipe', 21],
         ['José', 27],
         ['Gustavo', 30],
         ['Fernando', 22]
        ]

dataframe_lista = pd.DataFrame(lista)

In [23]:
dataframe_lista.head()

          0   1
0     Pedro  20
1       Ana  21
2    Karina  19
3  Patricia  18
4    Carlos  23